window.MUNI_SEED_DATA = {
  "content": [
    {
      "id": 1,
      "kind": "actualidad",
      "title": "Inicio de mejoras en calles urbanas",
      "slug": "inicio-de-mejoras-en-calles-urbanas",
      "category": "obras-y-proyectos",
      "summary": "La Municipalidad presenta una intervención de mantenimiento vial en barrios priorizados.",
      "body": "Este contenido de muestra puede reemplazarse por una publicación oficial con fotografías, avances, responsables y fechas relevantes del proyecto.",
      "image_path": "images/news-street-work.jpg",
      "image_alt": "",
      "published_at": "2026-05-01",
      "event_date": "",
      "status": "published",
      "tags": "obras, infraestructura, barrios",
      "cta_label": "",
      "cta_url": "",
      "created_by": null,
      "updated_by": 1,
      "created_at": "2026-05-22T04:32:41Z",
      "updated_at": "2026-05-22T16:12:53Z"
    },
    {
      "id": 2,
      "kind": "actualidad",
      "title": "Campaña municipal de limpieza",
      "slug": "campana-municipal-de-limpieza",
      "category": "avisos",
      "summary": "Aviso ciudadano sobre jornada de limpieza y ornato.",
      "body": "La publicación puede incluir horarios, puntos de encuentro, recomendaciones y dependencias encargadas.",
      "image_path": "images/news-community.jpg",
      "image_alt": null,
      "published_at": "2026-05-05",
      "event_date": "",
      "status": "published",
      "tags": "ambiente, comunidad",
      "cta_label": null,
      "cta_url": null,
      "created_by": null,
      "updated_by": null,
      "created_at": "2026-05-22T04:32:41Z",
      "updated_at": "2026-05-22T04:32:41Z"
    },
    {
      "id": 3,
      "kind": "agenda",
      "title": "Sesión informativa comunitaria",
      "slug": "sesion-informativa-comunitaria",
      "category": "comunicados",
      "summary": "Actividad de agenda pública para informar a vecinos sobre servicios municipales.",
      "body": "Los eventos de agenda pueden reutilizarse editando la fecha, el texto y la imagen.",
      "image_path": "images/news-town-hall.jpg",
      "image_alt": null,
      "published_at": "2026-05-12",
      "event_date": "2026-06-15",
      "status": "published",
      "tags": "agenda, comunidad",
      "cta_label": null,
      "cta_url": null,
      "created_by": null,
      "updated_by": null,
      "created_at": "2026-05-22T04:32:41Z",
      "updated_at": "2026-05-22T04:32:41Z"
    }
  ],
  "services": [
    {
      "id": 1,
      "title": "Solicitud de constancia municipal",
      "slug": "solicitud-de-constancia-municipal",
      "department": "Secretaría Municipal",
      "summary": "Información para solicitar constancias emitidas por la Municipalidad.",
      "requirements": "Documento de identidad vigente\nDatos exactos que deben constar en la certificación\nComprobante de pago si aplica",
      "steps": "Presentarse en Secretaría Municipal\nIndicar el tipo de constancia requerida\nRealizar pago de tasa si corresponde\nRetirar el documento en el plazo indicado",
      "cost": "Según tasa municipal vigente",
      "estimated_time": "1 a 3 días hábiles",
      "schedule": "lunes a viernes, horario administrativo",
      "location": "Edificio municipal",
      "contact": "Secretaría Municipal",
      "document_url": null,
      "status": "published",
      "tags": "tramites, constancias",
      "created_by": null,
      "updated_by": null,
      "created_at": "2026-05-22T04:32:41Z",
      "updated_at": "2026-05-22T04:32:41Z"
    },
    {
      "id": 2,
      "title": "Pago de tasas municipales",
      "slug": "pago-de-tasas-municipales",
      "department": "Tesorería Municipal",
      "summary": "Pasos para consultar y pagar tasas o servicios municipales.",
      "requirements": "Identificación del contribuyente\nClave catastral o referencia del servicio cuando aplique",
      "steps": "Solicitar estado de cuenta\nVerificar monto pendiente\nRealizar pago en Tesorería\nConservar recibo oficial",
      "cost": "Variable según servicio",
      "estimated_time": "Atención inmediata",
      "schedule": "lunes a viernes, horario administrativo",
      "location": "Tesorería Municipal",
      "contact": "Tesorería Municipal",
      "document_url": null,
      "status": "published",
      "tags": "pagos, tesoreria",
      "created_by": null,
      "updated_by": null,
      "created_at": "2026-05-22T04:32:41Z",
      "updated_at": "2026-05-22T04:32:41Z"
    }
  ],
  "documents": [
    {
      "id": 1,
      "title": "Ejemplo de documento de transparencia",
      "slug": "ejemplo-documento-transparencia",
      "category": "informes",
      "description": "Ficha de muestra para reemplazar por un PDF oficial cuando el municipio cargue sus documentos.",
      "document_date": "2026-01-15",
      "year": 2026,
      "department": "Secretaría Municipal",
      "file_path": null,
      "external_url": null,
      "status": "published",
      "tags": "transparencia, informe",
      "created_by": null,
      "updated_by": null,
      "created_at": "2026-05-22T04:32:41Z",
      "updated_at": "2026-05-22T04:32:41Z"
    }
  ],
  "mayors": [
    {
      "id": 1,
      "name": "Carmen Georgina Bautista Claros",
      "slug": "autoridad-municipal-actual",
      "period_start": "2026",
      "period_end": "",
      "biography": "Carmen Georgina Bautista Claros es una líder política hondureña y actual alcaldesa del municipio de Marcala, en el departamento de La Paz, para el período constitucional 2026-2030. Su ascenso a la titularidad de la corporación municipal marca un hito en la representación femenina de la región y consolida su liderazgo dentro del Partido Nacional de Honduras.\r\n\r\nTrayectoria Política y Elección\r\nAfiliada al Partido Nacional, Bautista Claros construyó su camino hacia la alcaldía mediante un fuerte trabajo comunitario y una campaña enfocada en las necesidades estructurales de Marcala. Tras resultar electa en los comicios generales, asumió oficialmente su cargo en enero de 2026, sucediendo a las administraciones anteriores con la promesa de una gestión transparente y orientada al desarrollo local.\r\n\r\nEjes de Gestión y Visión\r\nDesde el inicio de su mandato en 2026, su plan de gobierno se ha centrado en dinamizar la economía de Marcala, una región clave por su alta producción de café de calidad internacional. Entre sus prioridades principales destacan:\r\n\r\n-Infraestructura Vial: El mejoramiento y pavimentación de las carreteras y accesos rurales para facilitar el comercio.\r\n-Apoyo Social: La implementación de programas de asistencia para sectores vulnerables del municipio.\r\n-Fortalecimiento Institucional: La modernización de los servicios municipales para los ciudadanos.\r\n\r\nComo una de las pocas mujeres al frente de una alcaldía en el departamento de La Paz en el ciclo actual, Carmen Bautista es una figura clave en la política local, enfocada en transformar a Marcala en un municipio más próspero y conectado.",
      "photo_path": "images/20260522154017-WhatsApp_Image_2026-05-22_at_9.32.07_AM.jpeg",
      "is_current": 0,
      "status": "published",
      "tags": "municipalidad, gestion",
      "created_by": null,
      "updated_by": 1,
      "created_at": "2026-05-22T04:32:41Z",
      "updated_at": "2026-05-22T16:32:00Z"
    },
    {
      "id": 2,
      "name": "yo no sé",
      "slug": "www-google-com",
      "period_start": "2000",
      "period_end": "2004",
      "biography": "asdasd  asdasdhfdhasd fdfgd dfhdfhdfh",
      "photo_path": "images/20260522151216-apps.37393.13876487648548738.cbdadb4c-8335-4699-876e-68e010df4b84.jpeg",
      "is_current": 0,
      "status": "published",
      "tags": "",
      "created_by": 1,
      "updated_by": 1,
      "created_at": "2026-05-22T04:37:01Z",
      "updated_at": "2026-05-23T05:25:38Z"
    }
  ],
  "municipal_authorities": [
    {
      "id": 1,
      "name": "Miembro de la corporación municipal",
      "slug": "miembro-corporacion-municipal",
      "position": "Regiduría municipal",
      "area": "Corporación Municipal",
      "period": "2026-2030",
      "phone": "",
      "email": "",
      "biography": "Ficha editable para cargar los miembros actuales de la corporación municipal con fotografía, cargo, contacto y reseña pública.",
      "photo_path": "",
      "sort_order": 20,
      "status": "published",
      "tags": "corporacion, municipalidad",
      "created_by": null,
      "updated_by": null,
      "created_at": "2026-05-23T14:11:44Z",
      "updated_at": "2026-05-23T14:11:44Z"
    }
  ],
  "contacts": [
    {
      "id": 1,
      "name": "Atención ciudadana",
      "slug": "atencion-ciudadana",
      "area": "Secretaría Municipal",
      "position": "Ventanilla de información",
      "phone": "+504 0000-0000",
      "email": "info@municipalidadmarcala.hn",
      "office": "Palacio Municipal",
      "bio": "Contacto de muestra para orientar a la ciudadanía. Puede reemplazarse por autoridades, jefaturas o empleados con datos oficiales.",
      "photo_path": "",
      "sort_order": 10,
      "status": "published",
      "tags": "contacto, atencion",
      "created_by": null,
      "updated_by": null,
      "created_at": "2026-05-23T12:47:41Z",
      "updated_at": "2026-05-23T12:47:41Z"
    }
  ]
};
